version: "3" 
services:
  # Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
      - "./php/config/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=${ENV_MYSQL_USER}
      - MYSQL_PASS=${ENV_MYSQL_PASS}
  
  # Data persistence service layer
  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
      #- "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}

volumes:
  db_data: